# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yufujimoto/Desktop/Kiban/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 310)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_in_dir = QtWidgets.QLabel(self.centralwidget)
        self.lbl_in_dir.setMinimumSize(QtCore.QSize(120, 0))
        self.lbl_in_dir.setObjectName("lbl_in_dir")
        self.horizontalLayout_2.addWidget(self.lbl_in_dir)
        self.tbx_in_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.tbx_in_dir.setObjectName("tbx_in_dir")
        self.horizontalLayout_2.addWidget(self.tbx_in_dir)
        self.btn_in_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_in_dir.setObjectName("btn_in_dir")
        self.horizontalLayout_2.addWidget(self.btn_in_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_out_dir = QtWidgets.QLabel(self.centralwidget)
        self.lbl_out_dir.setMinimumSize(QtCore.QSize(120, 0))
        self.lbl_out_dir.setObjectName("lbl_out_dir")
        self.horizontalLayout_3.addWidget(self.lbl_out_dir)
        self.tbx_out_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.tbx_out_dir.setObjectName("tbx_out_dir")
        self.horizontalLayout_3.addWidget(self.tbx_out_dir)
        self.btn_out_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_out_dir.setObjectName("btn_out_dir")
        self.horizontalLayout_3.addWidget(self.btn_out_dir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gbx_feat_type = QtWidgets.QGroupBox(self.centralwidget)
        self.gbx_feat_type.setObjectName("gbx_feat_type")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbx_feat_type)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rad_feat_type_base = QtWidgets.QRadioButton(self.gbx_feat_type)
        self.rad_feat_type_base.setObjectName("rad_feat_type_base")
        self.verticalLayout_3.addWidget(self.rad_feat_type_base)
        self.rad_feat_type_mesh = QtWidgets.QRadioButton(self.gbx_feat_type)
        self.rad_feat_type_mesh.setObjectName("rad_feat_type_mesh")
        self.verticalLayout_3.addWidget(self.rad_feat_type_mesh)
        self.horizontalLayout_6.addWidget(self.gbx_feat_type)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.btn_convert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_convert.setObjectName("btn_convert")
        self.verticalLayout.addWidget(self.btn_convert)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_proc_files = QtWidgets.QLabel(self.centralwidget)
        self.lbl_proc_files.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_proc_files.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_proc_files.setObjectName("lbl_proc_files")
        self.horizontalLayout_5.addWidget(self.lbl_proc_files)
        self.pbr_proc_files = QtWidgets.QProgressBar(self.centralwidget)
        self.pbr_proc_files.setProperty("value", 24)
        self.pbr_proc_files.setObjectName("pbr_proc_files")
        self.horizontalLayout_5.addWidget(self.pbr_proc_files)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_in_dir.setText(_translate("MainWindow", "Input Directory"))
        self.btn_in_dir.setText(_translate("MainWindow", "Browse"))
        self.lbl_out_dir.setText(_translate("MainWindow", "Output Directory"))
        self.btn_out_dir.setText(_translate("MainWindow", "Browse"))
        self.gbx_feat_type.setTitle(_translate("MainWindow", "Feature Type"))
        self.rad_feat_type_base.setText(_translate("MainWindow", "Base Items"))
        self.rad_feat_type_mesh.setText(_translate("MainWindow", "DEM Items"))
        self.btn_convert.setText(_translate("MainWindow", "Convert!!"))
        self.lbl_proc_files.setText(_translate("MainWindow", "Files"))

